### ISSUE TITLE
survey not related to extension, time estimate wildly innacurate

### ISSUE THREAD

**Issue by rcrath** [erickaakcire/webhistorian#10]
When I took the survey, I expected something about the plugin that would be useful to development, not a general political survey asking for my uniquely Identifying and personal info like DOB, which combined with browser history is a real security issue.  involves way too much trust.  In addition, the segue from browser habits to political beliefs is jarring and unexpected.  Solicitation to participate in survey should include description of what the survey is about.  Misleading/not describing, while technically not dishonest, does induce mistrust.

The time estimate of five minutes is grossly inaccurate.  would suggest user testing this and timeine it to provide more accurate estimate and feedback regarding the survey.

I really like the extension, and it could be really useful, but the participation part is invasive and fosters mistrust to the point that I have misgivings about accidentally uploading my data and concerns that there are security issues when the survey data is combined with the browser history.  requires too much trust, and the misleading participation nags ( #9 ) further augment that mistrust.

**Comment by erickaakcire** [comment]
Hello,
Thanks for participating in the project and for your feedback. The topics the survey will cover are described on the first screen of the survey, which I realize is a lengthy document. This is the required format that went through the institutional review board process for research, which I believe should be modified for today's digital environments, but nonetheless I am required to use this format to describe the content of the survey, which is fully described. I will look to see if I can describe it further in the survey itself. 

Just to be clear the survey does not ask for date of birth, only year of birth and based on your helpful feedback I have modified that question to only ask for an age range, not an exact year. 

The survey adapts to your answers, so depending on your responses and your thoughtfulness (greatly appreciated) it could take more than 5 minutes, but the median time of completion is currently five minutes and 10 seconds, with some significant variation on the high end, which can come from people coming and going while completing the survey.

Regarding the participation nags, of course it could be annoying, but they can be disabled in the settings. Please see response to [issue 9](https://github.com/erickaakcire/webhistorian/issues/9). 

Thanks again, and please let me know if there is anything further that can be done to increase trust in the project.

**Comment by rcrath** [comment]
Thanks.
