### ISSUE TITLE
nag screen is annoying

### ISSUE THREAD

**Issue by rcrath** [erickaakcire/webhistorian#9]
Constantly opening an unsolicited browser window is annoying, usually would mean I would instantly uninstall.  But I really like the plugin.  SHould have a notice making clear that it will open a nag screen whenever you open it until you participate.  I accidentally uploaded my data eventually.  While this may in theory get more data, it is poor form.  If the price of using the plugin is that there will be nags or participation, this should be made clear on installation.  While I am usually not a fan of mul;tiple dialog windows, an "are you sure you want to upload your browser history," perhaps even one that requires typing out "yes" would be helpful here, rather than autofocusing on "all your date are come to us" followed by immediate upload.  Also, would be helpful to have a way to delete one's data if uploaded accidentally.

Please, this is an excellent and useful plugin. make it more user-centered or make clear that it is as much about getting our data as it is about providing a useful plugin.  acts as a sort of trojan the way currently implemented.

**Comment by erickaakcire** [comment]
Thanks for your comment and I'm glad you are finding the extension useful. There is an opt-out of research reminders option in the 'Settings' screen. You won't see it once you contribute but it is there beforehand. I believe it only does this once per browser session - so there is one reminder popup when your mouse leaves the browser window the first time, but it doesn't pop-up again until you close it and open it again. 

Thanks also for the feedback about the upload process. Based on your comment I'm working right now to provide a delete option on the server in case of unintended data contributions. I'll provide and update when that is online. 

The extension would not exist without the research project. I hope that is clear from our current materials, but it's hard to get at both the individual benefits and the research benefits in a short promotional message. I will try to make that crystal clear going forward, and thanks again!

**Comment by rcrath** [comment]
@erickaakcire thank you for the thoughtful responses. Maybe it says this in the extension page (I'm on a tablet at the moment) , but where can I find out more about the research project?

**Comment by erickaakcire** [comment]
@rcrath you're welcome! http://www.webhistorian.org/participate/
